# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    
    # Prepare
    ensure_git_status_clean
    set_changelog
    sync_code_signing(type: "appstore")
    increment_build_number(
      build_number: latest_testflight_build_number + 1,
      xcodeproj: "Norminal.xcodeproj"
    )

    # Build
    build_app(scheme: "Norminal")
    
    # Distribute
    upload_to_testflight(
      groups: ["Group A", "Group B"]
    )

    # After
    add_git_tag(
      grouping: "testflight",
    )

    push_to_git_remote

    notification(subtitle: "The app has been distributed to the beta testers.", message: "Fastlane beta lane complete")
  end

  desc "Push a new alpha build to TestFlight"
  lane :alpha do
    
    # Prepare
    ensure_git_status_clean
    set_changelog
    sync_code_signing(type: "appstore")
    increment_build_number(
      build_number: latest_testflight_build_number + 1,
      xcodeproj: "Norminal.xcodeproj"
    )

    # Build
    build_app(scheme: "Norminal")
    
    # Distribute
    upload_to_testflight(
      groups: ["Group A"]
    )

    # After
    add_git_tag(
      grouping: "testflight",
    )

    push_to_git_remote

    notification(message: "The app has been distributed to the beta testers.", subtitle: "Fastlane beta lane complete")
  end

  error do |lane, exception, options|
    notification(message: "Lane #{lane} error: \"#{exception}\".", subtitle: "Fastlane #{lane} lane failed")
  end
end
