# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  before_all do |lane, options|
    # Prepare
    begin
      ensure_git_status_clean
    rescue
      git_commit(path: "*")
    end

    ensure_git_status_clean

    sync_code_signing(type: "appstore")
    increment_build_number(
      build_number: latest_testflight_build_number + 1,
      xcodeproj: "Norminal.xcodeproj"
    )

    # Build
    build_app(scheme: "Norminal")
  end

  desc "Push a new beta build to TestFlight"
  lane :beta do
    # Distribute
    upload_to_testflight(
      groups: ["Group A", "Group B"]
    )
  end

  desc "Push a new alpha build to TestFlight"
  lane :alpha do
    # Distribute
    upload_to_testflight(
      groups: ["Group A"]
    )
  end

  after_all do |lane, options|
    # After
    notification(message: "Add a changelog in the terminal window", subtitle: "Fastlane #{lane} lane needs a changelog")
    set_changelog
    add_git_tag(
      grouping: "testflight",
      prefix: "#{lane}-"
    )

    push_to_git_remote

    notification(message: "The app has been distributed to the #{lane} testers.", subtitle: "Fastlane #{lane} lane complete")
  end

  error do |lane, exception, options|
    notification(message: "Lane #{lane} error: \"#{exception}\".", subtitle: "Fastlane #{lane} lane failed")
  end
end
